name: Build Signed Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to Build'
        required: true

jobs:
  build-and-sign:
    runs-on: ubuntu-18.04
    
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          ref: master
      
      # Setup SDK
      - name: Set up SDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      # Build .aab file
      - name: Build GPlay AAB
        run: ./gradlew bundleRelease
      
      # Build .apk file
      - name: Build Standalone APK
        run: ./gradlew assembleRelease
      
      # Sign .aab file
      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_aab
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      # Sign .apk file
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        
      # Upload .aab file
      - name: Upload GPlay AAB
        uses: actions/upload-artifact@v2
        with:
          name: Photok ${{ github.event.inputs.version }} GPlay AAB
          path: ${{ steps.sign_aab.outputs.signedReleaseFile }}
      
      # Upload .apk file
      - name: Upload Standalone APK
        uses: actions/upload-artifact@v2
        with:
          name: Photok ${{ github.event.inputs.version }} Standalone APK
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
      
      # Upload to Nextcloud
      - name: Create Directory for Release
        run: curl -X MLCOL -u ${{ secrets.NEXTCLOUD_USERNMAE }}:${{ secrets.NEXTCLOUD_PASSWORD }} ${{ secrets.NEXTCLOUD_PHOTOK_URL }}/${{ github.event.inputs.version }}

      - name: Upload AAB
        run: curl -T -u ${{ secrets.NEXTCLOUD_USERNMAE }}:${{ secrets.NEXTCLOUD_PASSWORD }} ${{ steps.sign_aab.outputs.signedReleaseFile }} ${{ secrets.NEXTCLOUD_PHOTOK_URL }}/${{ github.event.inputs.version }}
      
      - name: Upload APK
        run: curl -T -u ${{ secrets.NEXTCLOUD_USERNMAE }}:${{ secrets.NEXTCLOUD_PASSWORD }} ${{ steps.sign_apk.outputs.signedReleaseFile }} ${{ secrets.NEXTCLOUD_PHOTOK_URL }}/${{ github.event.inputs.version }}

