name: Create RC Branch

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-18.4
    
    steps:
    
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: test/${{ github.event.inputs.version }}
      
